@startuml Flow
actor User
participant Web
participant Queue
participant Consumer
participant Database

== Storing ==

User -> Web: Save Data
Web -> Queue
Web -> User: Response Ok
... async ...
Queue -> Consumer
Consumer -> Database

== Retrieving ==

User -> Web: Request Data
Web -> Database
Database -> Web
Web -> User: Response Ok

@enduml