
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln ./
COPY Audit.Consumer/*.csproj ./Audit.Consumer/
COPY Audit.Core/*.csproj ./Audit.Core/
COPY Audit.RabbitMQ/*.csproj ./Audit.RabbitMQ/
COPY Audit.Web/*.csproj ./Audit.Web/
COPY Audit.ElasticSearch/*.csproj ./Audit.ElasticSearch/

RUN dotnet restore

COPY . ./
RUN dotnet publish Audit.Web -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Audit.Web.dll"]