version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:80"
    depends_on:
      - rabbitMQ
  rabbitMQ:
    image: rabbitmq:3-management
    # hostname: rabbitmq_host
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticSearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitMQ
      - web
